/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2017-04-03 04:03:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.template.homepage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/E:/Web%20Personal/.metadata/.plugins/org.eclipse.wst.server.core/tmp3/wtpwebapps/ShoppingWeb/WEB-INF/lib/spring-security-taglibs-4.0.1.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1429699578000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-4.0.1.RELEASE.jar", Long.valueOf(1488525922836L));
    _jspx_dependants.put("jar:file:/E:/Web%20Personal/.metadata/.plugins/org.eclipse.wst.server.core/tmp3/wtpwebapps/ShoppingWeb/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1477708366774L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.2.0.RELEASE.jar", Long.valueOf(1478270571018L));
    _jspx_dependants.put("jar:file:/E:/Web%20Personal/.metadata/.plugins/org.eclipse.wst.server.core/tmp3/wtpwebapps/ShoppingWeb/WEB-INF/lib/spring-webmvc-4.2.0.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1438281382000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--HEADER-->\r\n");
      out.write(" <div class=\"header_top_bg\">\r\n");
      out.write("        <div class=\"container no-padding\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm-2\"></div>\r\n");
      out.write("                <div class=\"col-sm-6\"></div>\r\n");
      out.write("                <div class=\"col-sm-4 header_account_reponsive\">\r\n");
      out.write("                    <div class=\"header_top_account pull-right\">\r\n");
      out.write("                        \t<ul class=\"nav nav-pills\">\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <section class=\"header_middle\">\r\n");
      out.write("           <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-sm-3\">\r\n");
      out.write("                        <div class=\"header_logo\">\r\n");
      out.write("                           <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/images/logo/int-logo.png\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-6\">\r\n");
      out.write("                        <div class=\"header_search\">\r\n");
      out.write("                        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/searchname\">\r\n");
      out.write("                            <div class=\"input-group input_find\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" placeholder=\"Search for...\" name=\"name\">\r\n");
      out.write("                        <span class=\"input-group-btn\">\r\n");
      out.write("                            <button class=\"btn btn-default\" type=\"submit\"><i class=\"glyphicon glyphicon-search\"></i></button>\r\n");
      out.write("                        </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-3\">\r\n");
      out.write("                    <div class=\"header_middle_item pull-right\">\r\n");
      out.write("                        <div class=\"header_middle_cart\" id=\"header_middle_cart\" >\r\n");
      out.write("                            <a href=\"#\" class=\"cart_link\" >\r\n");
      out.write("                                <i class=\"fa fa-shopping-cart cart-icon\"></i>\r\n");
      out.write("                                <b>Giỏ hàng</b>\r\n");
      out.write("                                <span class=\"cart_quantity\">5</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                           \r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                 </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </section>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("     <div class=\"col-sm-4\" id=\"cart_toggle\">\r\n");
      out.write("         <div class=\"main-content-cart\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("            <div class=\"col-sm-4\"></div>\r\n");
      out.write("                <div class=\"col-sm-4\">\r\n");
      out.write("                <ul class=\"cart_menu_main\">\r\n");
      out.write("               <li class=\"cart_menu_toggle\">\r\n");
      out.write("                  <span class=\"item\">\r\n");
      out.write("                    <span class=\"item-left\">\r\n");
      out.write("                        <img src=\"http://lorempixel.com/50/50/\" alt=\"\" />\r\n");
      out.write("                        <span class=\"item-info\">\r\n");
      out.write("                            <span>Item name</span>\r\n");
      out.write("                            <span>23$</span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span class=\"item-right\">\r\n");
      out.write("                        <button class=\"btn btn-xs btn-danger pull-right\">x</button>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </span>\r\n");
      out.write("              </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("   <div class=\"header_menu_bg\">\r\n");
      out.write("       <div class=\"container no-padding\">\r\n");
      out.write("           <div class=\"main_menu_bg\">\r\n");
      out.write("                <div class=\"main_menu_item\">\r\n");
      out.write("                   <a href=\"#\" class=\"main_menu_item_active\">Home</a>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"main_menu_item\">\r\n");
      out.write("                   <a href=\"#\" class=\"main_menu_item_link\">Công nghệ<span class=\"laptop_item\">Laptop</span></a>\r\n");
      out.write("               </div>\r\n");
      out.write("                <div class=\"main_menu_item\" id=\"main_menu\" >\r\n");
      out.write("                   <a href=\"#\" class=\"main_menu_item_link\">Thời trang<span class=\"fashion_item\">Thời trang</span></a>\r\n");
      out.write("                    <div class=\"sub_menu_bg hidden-xs\" id=\"show_main_menu\">\r\n");
      out.write("                        <div class=\"sub_menu_col\" >\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_title\">Thời trang nam</a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo sơ mi nam</span></a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo thun nam</span></a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo body nam</span></a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo khoác nam</span></a>\r\n");
      out.write("                        </div> \r\n");
      out.write("                          <div class=\"sub_menu_col\" >\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_title\">Thời trang nam</a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo sơ mi nam</span></a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo thun nam</span></a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo body nam</span></a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo khoác nam</span></a>\r\n");
      out.write("                        </div> \r\n");
      out.write("                          <div class=\"sub_menu_col\" >\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_title\">Thời trang nam</a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo sơ mi nam</span></a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo thun nam</span></a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo body nam</span></a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo khoác nam</span></a>\r\n");
      out.write("                        </div> \r\n");
      out.write("                    </div>\r\n");
      out.write("               </div>\r\n");
      out.write("                <div class=\"main_menu_item\">\r\n");
      out.write("                   <a href=\"#\" class=\"main_menu_item_link\">Đồng hồ<span class=\"watch_item\">Đồng hồ</span></a>\r\n");
      out.write("               </div>\r\n");
      out.write("                <div class=\"main_menu_item\" id=\"main_menu1\">\r\n");
      out.write("                   <a href=\"#\" class=\"main_menu_item_link\">Giày dép<span class=\"shoe_item\">Giày dép</span></a>\r\n");
      out.write("                       <div class=\"sub_menu_bg hidden-xs\" id=\"show_main_menu1\">\r\n");
      out.write("                        <div class=\"sub_menu_col\" >\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_title\">Thời trang nam</a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo sơ mi nam</span></a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo thun nam</span></a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo body nam</span></a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo khoác nam</span></a>\r\n");
      out.write("                        </div> \r\n");
      out.write("                          <div class=\"sub_menu_col\" >\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_title\">Thời trang nam</a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo sơ mi nam</span></a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo thun nam</span></a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo body nam</span></a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo khoác nam</span></a>\r\n");
      out.write("                        </div> \r\n");
      out.write("                          <div class=\"sub_menu_col\" >\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_title\">Thời trang nam</a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo sơ mi nam</span></a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo thun nam</span></a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo body nam</span></a>\r\n");
      out.write("                            <a href=\"#\" class=\"sub_menu_col_item\"><span>Áo khoác nam</span></a>\r\n");
      out.write("                        </div> \r\n");
      out.write("                    </div>\r\n");
      out.write("               </div>\r\n");
      out.write("                <div class=\"main_menu_item\">\r\n");
      out.write("                   <a href=\"#\" class=\"main_menu_item_link\">Sắc đẹp<span class=\"beauty_item\">Sắc đẹp</span></a>\r\n");
      out.write("               </div>\r\n");
      out.write("                <div class=\"main_menu_item\">\r\n");
      out.write("                   <a href=\"#\" class=\"main_menu_item_link\">Trang sức<span class=\"jewelry_item\">Trang sức</span></a>\r\n");
      out.write("               </div>\r\n");
      out.write("                <div class=\"main_menu_item\">\r\n");
      out.write("                   <a href=\"#\" class=\"main_menu_item_link\">Trẻ em<span class=\"child_item\">Trẻ em</span></a>\r\n");
      out.write("               </div>\r\n");
      out.write("           </div>\r\n");
      out.write("       </div>\r\n");
      out.write("         <a href=\"#\" id=\"pull\" class=\"menu_reponsive\">Menu</a>\r\n");
      out.write("    </div>\r\n");
      out.write("<!--    END HEADER-->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /view/template/homepage/header.jsp(15,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name !=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t<li class=\"check_order\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"check_order_link\">Kiểm tra đơn hàng</a>\r\n");
        out.write("\t\t\t\t\t\t\t\t</li>\r\n");
        out.write("\t\t\t\t\t\t\t<li class=\"personal-setting\"><a\r\n");
        out.write("\t\t\t\t\t\t\t\thref=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/profile\"\r\n");
        out.write("\t\t\t\t\t\t\t\tclass=\"personal-profile\">Chào\r\n");
        out.write("\t\t\t\t\t\t\t\t\t");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle user_avat_toggle\"\r\n");
        out.write("\t\t\t\t\t\t\t\tdata-toggle=\"dropdown\"> <img alt=\"\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\tsrc=\"resource/images/avatar/google_avatar.png\" height=\"27\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\twidth=\"27\" data-ytimg=\"1\" onload=\";__ytRIL(this)\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\taria-hidden=\"true\"> <!--  <b class=\"caret\"></b> --></a>\r\n");
        out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu item-settings\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t");
        if (_jspx_meth_security_005fauthorize_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<li class=\"personal-setting\"><a class=\"personal-profile\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\thref=\"\"> Cài đặt</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<li><form id=\"logoutForm\" method=\"POST\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\taction=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/logout\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" />\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t</form></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<li class=\"personal-setting\"><a class=\"personal-profile\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"document.forms['logoutForm'].submit()\">Đăng xuất</a></li>\r\n");
        out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_security_005fauthorize_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_security_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    _jspx_th_security_005fauthorize_005f0.setPageContext(_jspx_page_context);
    _jspx_th_security_005fauthorize_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /view/template/homepage/header.jsp(29,9) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_security_005fauthorize_005f0.setAccess("isAuthenticated()");
    int _jspx_eval_security_005fauthorize_005f0 = _jspx_th_security_005fauthorize_005f0.doStartTag();
    if (_jspx_eval_security_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${current=='profile' ? 'active' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" personal-setting\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"personal-profile\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/profile\">Trang\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tcá nhân</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
    }
    if (_jspx_th_security_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.reuse(_jspx_th_security_005fauthorize_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fsecurity_005fauthorize_0026_005faccess.reuse(_jspx_th_security_005fauthorize_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /view/template/homepage/header.jsp(47,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.userPrincipal.name ==null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t   <div class=\"header_top_account\">\r\n");
        out.write("                        <div class=\"header_login_top pull-right\">\r\n");
        out.write("                            <a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/login\" class=\"header_login_link\"><i class=\"fa fa-lock\"></i>Đăng nhập/Đăng ký</a>\r\n");
        out.write("                        </div>\r\n");
        out.write("                         <div class=\"header_login pull-right\">\r\n");
        out.write("                            <a href=\"#\" class=\"header_login_link\"><i class=\"fa fa-user\"></i>Tài khoản của tôi</a>\r\n");
        out.write("                        </div>\r\n");
        out.write("                    </div>\r\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
